version: '3.9'

volumes:
  doko3000-couchdb-config:
  doko3000-couchdb-data:

services:
  doko3000:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: doko3000
    restart: always
    depends_on:
      - couchdb
    ports:
      - "80:5000"
    environment:
      - HOST=${HOST:-localhost}
      - SECRET_KEY=${SECRET_KEY:-change_me}
      - COUCHDB_URL=http://couchdb:5984
      - COUCHDB_DATABASE=${COUCHDB_DATABASE:-doko3000}
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-doko3000}
  couchdb:
    image: couchdb:3
    container_name: doko3000-couchdb
    restart: always
    ports:
      - "5984:5984"
    volumes:
      - doko3000-couchdb-data:/opt/couchdb/data
      - doko3000-couchdb-config:/opt/couchdb/etc/local.d
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-doko3000}
