version: '3.9'

networks:
  doko3000:
    name: doko3000

volumes:
  doko3000-couchdb-config:
  doko3000-couchdb-data:

services:
  doko3000:
    build: ..
    image: doko3000
    container_name: doko3000
    restart: always
    depends_on:
      - couchdb
    networks:
      - doko3000
    environment:
      - HOST=${HOST:-localhost}
      - SECRET_KEY=${SECRET_KEY:-change_me}
      - COUCHDB_URL=http://couchdb:5984
      - COUCHDB_DATABASE=${COUCHDB_DATABASE:-doko3000}
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-doko3000}
  couchdb:
    image: couchdb:3
    container_name: doko3000-couchdb
    restart: always
    volumes:
      - doko3000-couchdb-data:/opt/couchdb/data
      - doko3000-couchdb-config:/opt/couchdb/etc/local.d
    networks:
      - doko3000
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-doko3000}
  nginx:
    image: nginx:stable-alpine
    container_name: doko3000-nginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx-https.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./key.pem:/etc/nginx/key.pem
      - ../doko3000/static:/usr/share/nginx/html/static
    restart: always
    networks:
      - doko3000
